/* 小小科学乐园 · 游戏目录
 * 学科: 物理 40 / 化学 25 / 数学 35
 * 学段: "5-8" | "9-11" | "12-14" | "15-18"
 * status: "done" 可玩 / "todo" 敬请期待
 * 课标映射参考: 2022 义务教育科学课标 / NGSS DCI
 */
const GAMES = [
  /* ============ 已完成 ============ */
  { id:"optics",    title:"光的色散实验室", icon:"🔦", subject:"物理", grade:"9-11",  status:"done", file:"optics.html",
    desc:"棱镜、透镜、平面镜、彩色激光——把白光变成彩虹" },
  { id:"circuit",   title:"电路实验室",     icon:"🔋", subject:"物理", grade:"9-11",  status:"done", file:"circuit.html",
    desc:"电池、灯泡、开关、风车——接通电路看电流奔跑" },
  { id:"pipes",     title:"水管小工匠",     icon:"🔧", subject:"物理", grade:"9-11",  status:"done", file:"pipes.html",
    desc:"组装彩色水管、挖地道，把水引到每一株植物" },
  { id:"billiards", title:"小小台球手",     icon:"🎱", subject:"物理", grade:"12-14", status:"done", file:"billiards.html",
    desc:"碰撞与动量直觉——瞄准线帮你看清球路" },
  { id:"bowling",   title:"保龄球小将",     icon:"🎳", subject:"物理", grade:"12-14", status:"done", file:"bowling.html",
    desc:"运动与冲量——按住蓄力，全中最威风" },

  /* ============ 物理 · 5-8 岁 ============ */
  { id:"shadow-light",   title:"影子与光",     icon:"👤", subject:"物理", grade:"5-8", status:"done", file:"shadow-light.html",
    desc:"拖动物体和光源，看影子怎么变大变小" },
  { id:"magnet",         title:"磁铁吸什么",   icon:"🧲", subject:"物理", grade:"5-8", status:"done", file:"magnet.html",
    desc:"用磁铁吸一吸，哪些东西会被吸住？" },
  { id:"sink-float",     title:"沉浮实验",     icon:"🛟", subject:"物理", grade:"5-8", status:"done", file:"sink-float.html",
    desc:"把东西丢进水里，猜它会沉还是浮" },
  { id:"push-pull",      title:"推与拉",       icon:"🫸", subject:"物理", grade:"5-8", status:"done", file:"push-pull.html",
    desc:"推一推拉一拉，力让物体动起来" },
  { id:"sound-pitch",    title:"声音的高低",   icon:"🎵", subject:"物理", grade:"5-8", status:"done", file:"sound-pitch.html",
    desc:"拨动长短不同的琴弦，听音高变化" },
  { id:"simple-circuit", title:"灯泡亮灭",     icon:"💡", subject:"物理", grade:"5-8", status:"done", file:"simple-circuit.html",
    desc:"最简单的电路：一节电池一个灯泡" },
  { id:"seesaw",         title:"平衡跷跷板",   icon:"⚖️", subject:"物理", grade:"5-8", status:"done", file:"seesaw.html",
    desc:"两边放上小动物，怎样让跷跷板平衡？" },

  /* ============ 物理 · 9-11 岁 ============ */
  { id:"lever-pulley",   title:"杠杆与滑轮",   icon:"🏗️", subject:"物理", grade:"9-11", status:"done", file:"lever-pulley.html",
    desc:"用杠杆和滑轮撬动重物，省力还是费力？" },
  { id:"friction-car",   title:"摩擦小车",     icon:"🚗", subject:"物理", grade:"9-11", status:"done", file:"friction-car.html",
    desc:"在毛巾、木头、冰面上推小车，哪个滑得远？" },
  { id:"spring-force",   title:"弹簧与弹力",   icon:"🌀", subject:"物理", grade:"9-11", status:"done", file:"spring-force.html",
    desc:"拉弹簧挂砝码，弹力有什么规律？" },
  { id:"heat-transfer",  title:"热传导",       icon:"🌡️", subject:"物理", grade:"9-11", status:"done", file:"heat-transfer.html",
    desc:"金属勺和木勺插进热水，哪头先烫？" },
  { id:"sound-vibrate",  title:"声音与振动",   icon:"〰️", subject:"物理", grade:"9-11", status:"done", file:"sound-vibrate.html",
    desc:"看见声音：让扬声器上的盐粒跳舞" },
  { id:"simple-machines",title:"简单机械组合", icon:"⚙️", subject:"物理", grade:"9-11", status:"done", file:"simple-machines.html",
    desc:"杠杆滑轮齿轮组合起来，造一台省力机器" },
  { id:"siphon",         title:"虹吸与水位",   icon:"🪠", subject:"物理", grade:"9-11", status:"done", file:"siphon.html",
    desc:"连通器里水往哪里流？虹吸怎么启动？" },
  { id:"sundial",        title:"日影计时",     icon:"🌞", subject:"物理", grade:"9-11", status:"done", file:"sundial.html",
    desc:"拖动太阳，看日晷的影子怎么报时" },

  /* ============ 物理 · 12-14 岁 ============ */
  { id:"motion-graph",   title:"匀速运动图像", icon:"📈", subject:"物理", grade:"12-14", status:"done", file:"motion-graph.html",
    desc:"拖小车跑一跑，画出 s-t 和 v-t 图像" },
  { id:"force-compose",  title:"力的合成",     icon:"🧭", subject:"物理", grade:"12-14", status:"done", file:"force-compose.html",
    desc:"两个力拉一个物体，合力怎么算？" },
  { id:"force-balance",  title:"二力平衡",     icon:"🤝", subject:"物理", grade:"12-14", status:"done", file:"force-balance.html",
    desc:"什么时候物体纹丝不动？平衡的条件" },
  { id:"pressure-buoy",  title:"压强与浮力",   icon:"🎈", subject:"物理", grade:"12-14", status:"done", file:"pressure-buoy.html",
    desc:"改变液体深度和密度，浮力怎么变？" },
  { id:"density-lab",    title:"密度鉴别",     icon:"🧪", subject:"物理", grade:"12-14", status:"done", file:"density-lab.html",
    desc:"称一称量一量，这块'金子'是真的吗？" },
  { id:"ohms-law",       title:"欧姆定律",     icon:"🔌", subject:"物理", grade:"12-14", status:"done", file:"ohms-law.html",
    desc:"调电压和电阻，看电流怎么变（电路升级版）" },
  { id:"lens-imaging",   title:"凸透镜成像",   icon:"🔍", subject:"物理", grade:"12-14", status:"done", file:"lens-imaging.html",
    desc:"移动蜡烛，看光屏上的像怎么变" },
  { id:"wave-resonance", title:"波形与共振",   icon:"🎼", subject:"物理", grade:"12-14", status:"done", file:"wave-resonance.html",
    desc:"拨动琴弦看波形，让玻璃杯共振" },
  { id:"energy-skate",   title:"能量滑板",     icon:"🛹", subject:"物理", grade:"12-14", status:"done", file:"energy-skate.html",
    desc:"搭滑板轨道，看动能势能怎么转化" },
  { id:"work-power",     title:"功与功率",     icon:"💪", subject:"物理", grade:"12-14", status:"done", file:"work-power.html",
    desc:"搬同样的东西上楼，谁做功快？" },
  { id:"heat-engine",    title:"简单热机",     icon:"🚂", subject:"物理", grade:"12-14", status:"done", file:"heat-engine.html",
    desc:"烧一壶蒸汽，推动小轮子转起来" },
  { id:"dispersion-plus",title:"色散进阶",     icon:"🌈", subject:"物理", grade:"12-14", status:"done", file:"dispersion-plus.html",
    desc:"不同介质的折射率，测量并计算" },

  /* ============ 物理 · 15-18 岁 ============ */
  { id:"projectile",     title:"抛体运动",     icon:"🏹", subject:"物理", grade:"15-18", status:"done", file:"projectile.html",
    desc:"调角度和初速度，命中远处的靶子" },
  { id:"momentum",       title:"动量守恒碰撞", icon:"💥", subject:"物理", grade:"15-18", status:"done", file:"momentum.html",
    desc:"弹性与非弹性碰撞，动量和能量去哪了？" },
  { id:"oscillation",    title:"振动与单摆",   icon:"⏰", subject:"物理", grade:"15-18", status:"done", file:"oscillation.html",
    desc:"弹簧振子和单摆的周期由什么决定？" },
  { id:"wave-interfere", title:"波的干涉",     icon:"🌊", subject:"物理", grade:"15-18", status:"done", file:"wave-interfere.html",
    desc:"两个波源相遇，哪里加强哪里减弱？" },
  { id:"electric-field", title:"电场与电势线", icon:"⚡", subject:"物理", grade:"15-18", status:"done", file:"electric-field.html",
    desc:"摆放电荷，看电场线和等势面" },
  { id:"induction",      title:"电磁感应发电", icon:"🔦", subject:"物理", grade:"15-18", status:"done", file:"induction.html",
    desc:"摇动磁铁穿过线圈，点亮小灯泡" },
  { id:"orbit",          title:"天体引力轨道", icon:"🪐", subject:"物理", grade:"15-18", status:"done", file:"orbit.html",
    desc:"给行星一个初速度，它能绕几圈？" },
  { id:"photoelectric",  title:"光电效应直觉", icon:"💡", subject:"物理", grade:"15-18", status:"done", file:"photoelectric.html",
    desc:"不同颜色的光照金属，能把电子打出来吗？" },

  /* ============ 化学 · 5-8 岁 ============ */
  { id:"three-states",   title:"三态变化",     icon:"🧊", subject:"化学", grade:"5-8", status:"done", file:"three-states.html",
    desc:"加热冰块看它变成水、变成汽" },
  { id:"mix-separate",   title:"混合与分离",   icon:"🥣", subject:"化学", grade:"5-8", status:"done", file:"mix-separate.html",
    desc:"沙子和盐混在一起了，怎么分开？" },
  { id:"dissolve-speed", title:"溶解快慢",     icon:"🍬", subject:"化学", grade:"5-8", status:"done", file:"dissolve-speed.html",
    desc:"搅拌、加热、碾碎，哪个让糖溶得快？" },

  /* ============ 化学 · 9-11 岁 ============ */
  { id:"build-molecule", title:"分子拼装",     icon:"🧬", subject:"化学", grade:"9-11", status:"done", file:"build-molecule.html",
    desc:"拖原子拼出水、氧气、二氧化碳分子" },
  { id:"build-atom",     title:"原子搭建",     icon:"⚛️", subject:"化学", grade:"9-11", status:"done", file:"build-atom.html",
    desc:"拖质子中子电子，搭出各种原子" },
  { id:"acid-base",      title:"酸碱指示剂",   icon:"🧫", subject:"化学", grade:"9-11", status:"done", file:"acid-base.html",
    desc:"紫甘蓝汁遇到不同液体会变什么颜色？" },
  { id:"filter-evap",    title:"过滤与蒸发",   icon:"🫙", subject:"化学", grade:"9-11", status:"done", file:"filter-evap.html",
    desc:"过滤泥沙、蒸发盐水，留下什么？" },
  { id:"combustion",     title:"燃烧条件",     icon:"🔥", subject:"化学", grade:"9-11", status:"done", file:"combustion.html",
    desc:"可燃物、氧气、温度，缺一不可" },
  { id:"metal-activity", title:"金属活动性",   icon:"🥇", subject:"化学", grade:"9-11", status:"done", file:"metal-activity.html",
    desc:"把铁钉放进硫酸铜，会发生什么？" },
  { id:"air-composition",title:"空气成分",     icon:"💨", subject:"化学", grade:"9-11", status:"done", file:"air-composition.html",
    desc:"钟罩里的蜡烛熄灭后，水面升多少？" },

  /* ============ 化学 · 12-14 岁 ============ */
  { id:"balance-eq",     title:"方程式配平",   icon:"🧮", subject:"化学", grade:"12-14", status:"done", file:"balance-eq.html",
    desc:"拖动原子团，让两边原子数相等" },
  { id:"concentration",  title:"浓度配制",     icon:"🧂", subject:"化学", grade:"12-14", status:"done", file:"concentration.html",
    desc:"称溶质、加溶剂，配出指定浓度" },
  { id:"titration",      title:"虚拟滴定",     icon:"💧", subject:"化学", grade:"12-14", status:"done", file:"titration.html",
    desc:"一滴一滴加，等指示剂变色就停" },
  { id:"displacement",   title:"金属置换",     icon:"🔄", subject:"化学", grade:"12-14", status:"done", file:"displacement.html",
    desc:"谁能把谁从溶液里置换出来？" },
  { id:"gas-prep",       title:"气体制取",     icon:"🎈", subject:"化学", grade:"12-14", status:"done", file:"gas-prep.html",
    desc:"拼装发生装置和收集装置制取气体" },
  { id:"solubility",     title:"溶解度曲线",   icon:"📉", subject:"化学", grade:"12-14", status:"done", file:"solubility.html",
    desc:"升温降温，看溶质溶进去还是析出来" },
  { id:"mass-conserve",  title:"质量守恒",     icon:"⚖️", subject:"化学", grade:"12-14", status:"done", file:"mass-conserve.html",
    desc:"反应前后称一称，质量变了吗？" },
  { id:"ph-color",       title:"pH 调色",      icon:"🎨", subject:"化学", grade:"12-14", status:"done", file:"ph-color.html",
    desc:"用 pH 试纸测一测身边溶液的酸碱性" },
  { id:"polarity",       title:"分子极性",     icon:"🧲", subject:"化学", grade:"12-14", status:"done", file:"polarity.html",
    desc:"为什么水会被带电的尺子吸引？" },
  { id:"periodic-hunt",  title:"周期表寻宝",   icon:"🗺️", subject:"化学", grade:"12-14", status:"done", file:"periodic-hunt.html",
    desc:"按线索在元素周期表里找元素" },

  /* ============ 化学 · 15-18 岁 ============ */
  { id:"reaction-rate",  title:"反应速率",     icon:"⏱️", subject:"化学", grade:"15-18", status:"done", file:"reaction-rate.html",
    desc:"温度和浓度怎么改变反应快慢？" },
  { id:"equilibrium",    title:"化学平衡",     icon:"⚖️", subject:"化学", grade:"15-18", status:"done", file:"equilibrium.html",
    desc:"改变条件，看平衡向哪边移动" },
  { id:"galvanic",       title:"原电池与电解", icon:"🔋", subject:"化学", grade:"15-18", status:"done", file:"galvanic.html",
    desc:"锌铜原电池怎么产生电流？" },
  { id:"titration-curve",title:"滴定曲线",     icon:"📊", subject:"化学", grade:"15-18", status:"done", file:"titration-curve.html",
    desc:"边滴定边画 pH 曲线，找突跃点" },
  { id:"organic-shape",  title:"有机分子构型", icon:"🧩", subject:"化学", grade:"15-18", status:"done", file:"organic-shape.html",
    desc:"拼甲烷乙醇，看碳原子的四面体" },

  /* ============ 数学 · 5-8 岁 ============ */
  { id:"make-ten",       title:"凑十大作战",   icon:"🔟", subject:"数学", grade:"5-8", status:"done", file:"make-ten.html",
    desc:"拖数字泡泡合在一起凑成十" },
  { id:"number-split",   title:"数字拆分",     icon:"✂️", subject:"数学", grade:"5-8", status:"done", file:"number-split.html",
    desc:"把 7 分成几和几？有几种分法？" },
  { id:"tangram",        title:"七巧板",       icon:"🧩", subject:"数学", grade:"5-8", status:"done", file:"tangram.html",
    desc:"七块板拼出小猫小船小房子" },
  { id:"symmetry",       title:"图形对称",     icon:"🦋", subject:"数学", grade:"5-8", status:"done", file:"symmetry.html",
    desc:"画出蝴蝶的另一半，找找对称轴" },
  { id:"sort-count",     title:"分类计数",     icon:"🧺", subject:"数学", grade:"5-8", status:"done", file:"sort-count.html",
    desc:"按颜色形状分一分，再数一数" },
  { id:"fraction-bar",   title:"分数条",       icon:"🍕", subject:"数学", grade:"5-8", status:"done", file:"fraction-bar.html",
    desc:"切开披萨，认识一半和四分之一" },
  { id:"area-fill",      title:"面积铺满",     icon:"🟦", subject:"数学", grade:"5-8", status:"done", file:"area-fill.html",
    desc:"用小方块铺满图形，数一数用了几块" },
  { id:"compare",        title:"比长短轻重",   icon:"📏", subject:"数学", grade:"5-8", status:"done", file:"compare.html",
    desc:"排一排哪个长哪个重" },
  { id:"pattern",        title:"简单规律",     icon:"🔷", subject:"数学", grade:"5-8", status:"done", file:"pattern.html",
    desc:"红黄蓝红黄蓝……下一个是什么？" },
  { id:"plinko-junior",  title:"弹珠直觉",     icon:"🎰", subject:"数学", grade:"5-8", status:"done", file:"plinko-junior.html",
    desc:"弹珠落下来，哪个槽里最多？" },

  /* ============ 数学 · 9-11 岁 ============ */
  { id:"fraction-eq",    title:"分数拼图与等值", icon:"🍰", subject:"数学", grade:"9-11", status:"done", file:"fraction-eq.html",
    desc:"1/2 和 2/4 原来一样大" },
  { id:"area-model",     title:"面积模型乘法", icon:"🟧", subject:"数学", grade:"9-11", status:"done", file:"area-model.html",
    desc:"用方格子看懂两位数乘法" },
  { id:"decimal-line",   title:"小数数轴",     icon:"📐", subject:"数学", grade:"9-11", status:"done", file:"decimal-line.html",
    desc:"把 0.5、1.25 放到数轴上的家" },
  { id:"protractor",     title:"角度量角器",   icon:"📐", subject:"数学", grade:"9-11", status:"done", file:"protractor.html",
    desc:"转动射线，读出角度，认识锐角钝角" },
  { id:"coord-plot",     title:"坐标描点",     icon:"🗺️", subject:"数学", grade:"9-11", status:"done", file:"coord-plot.html",
    desc:"按坐标找宝藏，描出小动物图案" },
  { id:"factor-multiple",title:"倍数与因数",   icon:"✖️", subject:"数学", grade:"9-11", status:"done", file:"factor-multiple.html",
    desc:"给数字找朋友：谁是它的因数？" },
  { id:"max-area",       title:"周长面积最大化", icon:"🏞️", subject:"数学", grade:"9-11", status:"done", file:"max-area.html",
    desc:"20 根篱笆围出最大的菜地" },
  { id:"chart-reading",  title:"图表读数",     icon:"📊", subject:"数学", grade:"9-11", status:"done", file:"chart-reading.html",
    desc:"读条形图折线图，回答小问题" },
  { id:"balance-intro",  title:"方程天平入门", icon:"⚖️", subject:"数学", grade:"9-11", status:"done", file:"balance-intro.html",
    desc:"天平两边同时拿掉，x 是几？" },
  { id:"tessellation",   title:"密铺",         icon:"🧱", subject:"数学", grade:"9-11", status:"done", file:"tessellation.html",
    desc:"哪些图形能不留缝地铺满地面？" },

  /* ============ 数学 · 12-14 岁 ============ */
  { id:"linear-graph",   title:"一次函数图像", icon:"📈", subject:"数学", grade:"12-14", status:"done", file:"linear-graph.html",
    desc:"拖 k 和 b，看直线怎么动" },
  { id:"eq-system",      title:"方程组天平",   icon:"⚖️", subject:"数学", grade:"12-14", status:"done", file:"eq-system.html",
    desc:"两个天平联立，解出 x 和 y" },
  { id:"ratio-mix",      title:"比例与配比",   icon:"🍹", subject:"数学", grade:"12-14", status:"done", file:"ratio-mix.html",
    desc:"调果汁：橙汁和水怎么配最好喝？" },
  { id:"pythagoras",     title:"勾股拼图",     icon:"📐", subject:"数学", grade:"12-14", status:"done", file:"pythagoras.html",
    desc:"拼一拼证明 a²+b²=c²" },
  { id:"circle-tangent", title:"圆与切线",     icon:"⭕", subject:"数学", grade:"12-14", status:"done", file:"circle-tangent.html",
    desc:"拖动直线靠近圆，相切时有什么性质？" },
  { id:"prob-wheel",     title:"概率转盘",     icon:"🎡", subject:"数学", grade:"12-14", status:"done", file:"prob-wheel.html",
    desc:"设计自己的转盘，看指针停在哪" },
  { id:"sampling",       title:"统计抽球",     icon:"🎱", subject:"数学", grade:"12-14", status:"done", file:"sampling.html",
    desc:"摸球 100 次，猜猜袋子里有几个红球" },
  { id:"transform",      title:"坐标变换",     icon:"🔀", subject:"数学", grade:"12-14", status:"done", file:"transform.html",
    desc:"平移旋转翻折，图形去哪了？" },
  { id:"function-machine",title:"函数机器",    icon:"🏭", subject:"数学", grade:"12-14", status:"done", file:"function-machine.html",
    desc:"数字放进机器，猜猜机器做了什么" },
  { id:"sequence",       title:"数列规律",     icon:"🔢", subject:"数学", grade:"12-14", status:"done", file:"sequence.html",
    desc:"2、4、8、16……下一个是什么？" },

  /* ============ 数学 · 15-18 岁 ============ */
  { id:"quadratic",      title:"二次函数与最值", icon:"⛰️", subject:"数学", grade:"15-18", status:"done", file:"quadratic.html",
    desc:"拖 a、b、c，抛物线怎么变？顶点在哪？" },
  { id:"unit-circle",    title:"三角函数单位圆", icon:"🎡", subject:"数学", grade:"15-18", status:"done", file:"unit-circle.html",
    desc:"转动半径，看 sin 和 cos 怎么变" },
  { id:"vector-add",     title:"向量加法",     icon:"➡️", subject:"数学", grade:"15-18", status:"done", file:"vector-add.html",
    desc:"首尾相接拖向量，画出平行四边形" },
  { id:"derivative",     title:"导数斜率直觉", icon:"🏂", subject:"数学", grade:"15-18", status:"done", file:"derivative.html",
    desc:"拖动切点，看切线斜率怎么变" },
  { id:"regression",     title:"回归与相关性", icon:"📉", subject:"数学", grade:"15-18", status:"done", file:"regression.html",
    desc:"散布点中拖出一条最合适的线" }
];
